### ISSUE TITLE
Missing conf file causing unhandeled exception

### ISSUE THREAD

**Issue by thuma** [46elks/elkme#8]
```
$ elkme --numbers
Traceback (most recent call last):
  File "/usr/local/bin/elkme", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/elkme/main.py", line 135, in main
    my_numbers(conf)
  File "/Library/Python/2.7/site-packages/elkme/elks.py", line 131, in my_numbers
    response = query_api(conf['username'], conf['password'], None, 'Numbers')
KeyError: 'username'
```

**Comment by johannesl** [comment]
Hereby confirming this bug still exists:

```
$ ./main.py 
Traceback (most recent call last):
  File "./main.py", line 191, in <module>
    main()
  File "./main.py", line 128, in main
    elks_conn = Elks(conf)
  File "/Users/jojo/github/elkme/elkme/elks.py", line 27, in __init__
    requires_elements(['username', 'password'], conf)
  File "/Users/jojo/github/elkme/elkme/helpers.py", line 39, in requires_elements
    raise KeyError('Missing values %s' % (err_msg))
KeyError: 'Missing values username, password'
```
